version: '3.9'

services:
  web:
    environment: 
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/mydatabase
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - flask_db
  
  flask_db:
    image: postgres
    container_name: flask_db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - flask_db:/var/lib/postgresql/data

volumes:
  flask_db: {}
