# Use the official Python image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Set environment variables
ENV FLASK_APP=app.main:create_app()
ENV FLASK_ENV=development

# Expose port 5000
EXPOSE 5000

# Command to run the Flask application
CMD ["python3", "app/main.py"]
